trigger:
- '*'

variables:
  major: 1
  minor: $[counter(variables['major'], 10)]
  build: $[counter(variables['minor'], 1000)]
  version: $[format('{0}.{1}.{2}', variables.major, variables.minor, variables.build)]

stages:
- stage: UnitTesting
  displayName: 'Run all unit tests.'
  jobs:
  - job: DotnetTesting
    displayName: 'Test the .NET code'
    pool:
      name: 'Windows'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restoring nuget packages'
      inputs:
        command: 'restore'
        projects: '$(Build.SourcesDirectory)/RealLoader.sln'

    # - task: DotNetCoreCLI@2
    #   displayName: 'Running dotnet unit tests'
    #   inputs:
    #     command: 'test'
    #     projects: '$(Build.SourcesDirectory)/RealLoader.sln'

# - ${{ if or(or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/developer')), eq(variables['Build.SourceBranch'], 'refs/heads/testing')) }}:
- stage: Build
  displayName: 'Build all artifacts for windows and linux'
  jobs:
  # Build for windows
  - job: BuildWindows
    displayName: 'Build on Windows'
    pool:
      name: 'Windows'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 9.x
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: DotNetCoreCLI@2
      displayName: 'Restoring nuget packages'
      inputs:
        command: 'restore'
        projects: '$(Build.SourcesDirectory)/RealLoader.sln'

    - task: MSBuild@1
      displayName: 'Build C++ Windows Solution'
      inputs:
        solution: '$(Build.SourcesDirectory)/RealLoader.sln'
        msbuildArchitecture: 'x64'
        platform: 'x64'
        configuration: 'Dist'
        msbuildArguments: '/target:Rebuild'

    - task: DotNetCoreCLI@2
      displayName: 'Build individual .NET projects'
      inputs:
        command: build
        projects: |
          $(Build.SourcesDirectory)/Tools/RealLoaderInstaller/RealLoaderInstaller.csproj
          $(Build.SourcesDirectory)/Tools/RealLoaderGuiInstaller/RealLoaderGuiInstaller.csproj
          $(Build.SourcesDirectory)/Mods/DotNetSdkBuilderMod/DotNetSdkBuilderMod.csproj
          $(Build.SourcesDirectory)/Framework/RealLoaderFramework/RealLoaderFramework.csproj
          $(Build.SourcesDirectory)/Framework/RealLoaderFramework.Sdk/RealLoaderFramework.Sdk.csproj

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/bin'
        ArtifactName: 'windows_artifacts'
        publishLocation: 'Container'

  # Build for linux
  - job: BuildLinux
    displayName: 'Build on Linux'
    pool:
      name: 'Linux'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 9.x
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: DotNetCoreCLI@2
      displayName: 'Restoring nuget packages'
      inputs:
        command: 'restore'
        projects: '$(Build.SourcesDirectory)/RealLoader.sln'

    - task: CMake@1
      displayName: 'CMake Configure'
      inputs:
        cmakeArgs: '$(Build.SourcesDirectory)'

    - task: CMake@1
      displayName: 'CMake Build'
      inputs:
        cmakeArgs: '--build $(Build.SourcesDirectory)/build'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/build'
        ArtifactName: 'linux_artifacts'
        publishLocation: 'Container'

# Deploy the artifacts to github with a new tag.
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
  - stage: Deploy
    displayName: 'Deploy built artifacts to GitHub'
    dependsOn: Build
    jobs:
    - job: DeployJob
      displayName: 'Deploy Artifacts'
      pool:
        name: 'Linux'
      steps:
      - task: DownloadBuildArtifacts@0
        displayName: 'Download Windows Artifacts'
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'windows_artifacts'
          downloadPath: '$(System.ArtifactsDirectory)'

      - task: DownloadBuildArtifacts@0
        displayName: 'Download Linux Artifacts'
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'linux_artifacts'
          downloadPath: '$(System.ArtifactsDirectory)'

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/windows_artifacts/Net/RealLoaderFramework/Release'
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/RealLoaderFramework.zip'

      - task: GitHubRelease@1
        displayName: 'Create GitHub Release'
        inputs:
          action: 'create'
          gitHubConnection: 'Realynx'
          repository: 'Realynx/RealLoader'
          tagSource: 'gitTag'
          tagPattern: 'v[0-9]+.[0-9]+.[0-9]+'
          title: 'Release $(version)-ci'
          assets: |
            $(System.ArtifactsDirectory)/ManagedModFramework.zip
            $(System.ArtifactsDirectory)/windows_artifacts/Windows/Bootstrapper.exe
            $(System.ArtifactsDirectory)/windows_artifacts/Windows/CLRHost.dll
            $(System.ArtifactsDirectory)/linux_artifacts/GithubSymbols/Linux/libCLRHost.so
