namespace Engine_5._1._1.CoreUObject.Flags {
    /// <summary>
    /// <see href="https://github.com/EpicGames/UnrealEngine/blob/5.1/Engine/Source/Runtime/CoreUObject/Public/UObject/ObjectMacros.h#L187"/>
    /// </summary>
    [Flags]
    public enum EClassFlags : uint {
        /// <summary> No Flags </summary>
        CLASS_None = 0x00000000u,

        /// <summary> Class is abstract and can't be instantiated directly. </summary>
        CLASS_Abstract = 0x00000001u,

        /// <summary> Save object configuration only to Default INIs, never to local INIs. Must be combined with CLASS_Config </summary>
        CLASS_DefaultConfig = 0x00000002u,

        /// <summary> Load object configuration at construction time. </summary>
        CLASS_Config = 0x00000004u,

        /// <summary> This object type can't be saved; null it out at save time. </summary>
        CLASS_Transient = 0x00000008u,

        /// <summary> This object type may not be available in certain context. (i.e. game runtime or in certain configuration). Optional class data is saved separately to other object types. (i.e. might use sidecar files) </summary>
        CLASS_Optional = 0x00000010u,

        /// <summary> </summary>
        CLASS_MatchedSerializers = 0x00000020u,

        /// <summary> Indicates that the config settings for this class will be saved to Project/User*.ini (similar to CLASS_GlobalUserConfig) </summary>
        CLASS_ProjectUserConfig = 0x00000040u,

        /// <summary> Class is a native class - native interfaces will have CLASS_Native set, but not RF_MarkAsNative </summary>
        CLASS_Native = 0x00000080u,

        /// <summary> Don't export to C++ header. </summary>
        [Obsolete("CLASS_NoExport should no longer be used. It is no longer being set by engine code.")]
        CLASS_NoExport = 0x00000100u,

        /// <summary> Do not allow users to create in the editor. </summary>
        CLASS_NotPlaceable = 0x00000200u,

        /// <summary> Handle object configuration on a per-object basis, rather than per-class. </summary>
        CLASS_PerObjectConfig = 0x00000400u,

        /// <summary> Whether SetUpRuntimeReplicationData still needs to be called for this class </summary>
        CLASS_ReplicationDataIsSetUp = 0x00000800u,

        /// <summary> Class can be constructed from editinline New button. </summary>
        CLASS_EditInlineNew = 0x00001000u,

        /// <summary> Display properties in the editor without using categories. </summary>
        CLASS_CollapseCategories = 0x00002000u,

        /// <summary> Class is an interface *</summary>
        CLASS_Interface = 0x00004000u,

        /// <summary>  Do not export a constructor for this class, assuming it is in the cpptext *</summary>
        [Obsolete("CLASS_CustomConstructor should no longer be used. It is no longer being set by engine code.")]
        CLASS_CustomConstructor = 0x00008000u,

        /// <summary> all properties and functions in this class are const and should be exported as const </summary>
        CLASS_Const = 0x00010000u,

        /// <summary> Class flag indicating objects of this class need deferred dependency loading </summary>
        CLASS_NeedsDeferredDependencyLoading = 0x00020000u,

        /// <summary> Indicates that the class was created from blueprint source material </summary>
        CLASS_CompiledFromBlueprint = 0x00040000u,

        /// <summary> Indicates that only the bare minimum bits of this class should be DLL exported/imported </summary>
        CLASS_MinimalAPI = 0x00080000u,

        /// <summary> Indicates this class must be DLL exported/imported (along with all of it's members) </summary>
        CLASS_RequiredAPI = 0x00100000u,

        /// <summary> Indicates that references to this class default to instanced. Used to be subclasses of UComponent, but now can be any UObject </summary>
        CLASS_DefaultToInstanced = 0x00200000u,

        /// <summary> Indicates that the parent token stream has been merged with ours. </summary>
        CLASS_TokenStreamAssembled = 0x00400000u,

        /// <summary> Class has component properties. </summary>
        CLASS_HasInstancedReference = 0x00800000u,

        /// <summary> Don't show this class in the editor class browser or edit inline new menus. </summary>
        CLASS_Hidden = 0x01000000u,

        /// <summary> Don't save objects of this class when serializing </summary>
        CLASS_Deprecated = 0x02000000u,

        /// <summary> Class not shown in editor drop down for class selection </summary>
        CLASS_HideDropDown = 0x04000000u,

        /// <summary> Class settings are saved to &lt;AppData>/..../Blah.ini (as opposed to CLASS_DefaultConfig) </summary>
        CLASS_GlobalUserConfig = 0x08000000u,

        /// <summary> Class was declared directly in C++ and has no boilerplate generated by UnrealHeaderTool </summary>
        CLASS_Intrinsic = 0x10000000u,

        /// <summary> Class has already been constructed (maybe in a previous DLL version before hot-reload). </summary>
        CLASS_Constructed = 0x20000000u,

        /// <summary> Indicates that object configuration will not check against ini base/defaults when serialized </summary>
        CLASS_ConfigDoNotCheckDefaults = 0x40000000u,

        /// <summary> Class has been consigned to oblivion as part of a blueprint recompile, and a newer version currently exists. </summary>
        CLASS_NewerVersionExists = 0x80000000u,
    }
}